jobs: 100
keep-going: False
restart-times: 0
rerun-incomplete: False
use-singularity: True
singularity-args: "-e --cleanenv -B /projects -B /data -B /beegfs-storage -B /projects/wp1/temp:/tmp "
singularity-prefix: "/projects/wp1/nobackup/singularity_cache"
drmaa: " -A wp1 -N 1-1 -t {resources.time} -n {resources.threads} --mem={resources.mem_mb} --mem-per-cpu={resources.mem_per_cpu} --mem-per-cpu={resources.mem_per_cpu} --partition={resources.partition} -J {rule} -e slurm_out/{rule}_%j.err -o slurm_out/{rule}_%j.out"
drmaa-log-dir: "slurm_out"
configfiles: ["config/config.yaml", "config/config.data.hg19.yaml"]
default-resources: "tmpdir='/projects/wp1/temp'"
