---

 filter_vcf:
   snv_soft_filter:
     path: "config/filters/config_soft_filter_uppsala_vep105.yaml"
   snv_hard_filter:
     path: "config/filters/config_hard_filter_uppsala_vep105.yaml"
   cnv_hard_filter_amp:
     path: "config/filters/config_hard_filter_cnv_amp.yaml"
   cnv_hard_filter_loh:
     path: "config/filters/config_hard_filter_cnv_loh.yaml"
   germline:
     path: "config/filters/config_hard_filter_germline_vep105.yaml"