---

 cnv_html_report:
   template:
     path: config/cnv_report_template.html

 filter_vcf:
   snv_soft_filter:
     path: "config/config_soft_filter_uppsala.yaml"
   snv_hard_filter:
     path: "config/config_hard_filter_uppsala.yaml"
   cnv_hard_filter_amp:
     path: "config/config_hard_filter_cnv_amp.yaml"
   cnv_hard_filter_loh:
     path: "config/config_hard_filter_cnv_loh.yaml"
   germline:
     path: "config/config_hard_filter_germline.yaml"