---
 svdb_query:
   db_string:
     checksum: 076f3a9bec5e9941eb4bbbf4594c0037
     path: SVDB/all_TN_292_svdb_0.8_20220505.vcf
     url: https://figshare.com/ndownloader/files/40882898?private_link=430129261fe3d472485b

 purecn:
   extra: 
     checksum: eb311461a92b53a9494bba9625ecd4c3
     path: purecn/mapping_bias_nextseq_27_hg19.rds
     url: https://figshare.com/ndownloader/files/40882865?private_link=430129261fe3d472485b

   normaldb:
     checksum: d77528e5bfeec40791235e52dcbed7ef
     path: purecn/normalDB_nextseq_27_hg19.rds
     url: https://figshare.com/ndownloader/files/40882874?private_link=430129261fe3d472485b


 gatk_denoise_read_counts:
   normal_reference:
      checksum: ab0a2f3276125c8695b72a2b2c5779ea
      path: PoN/gatk_cnv_novaseq_13.hdf5
      url: https://figshare.com/ndownloader/files/40882862?private_link=430129261fe3d472485b

 cnvkit_batch:
   normal_reference:
     checksum: e7853030e7a6b0ccbeffb7c008983a29
     path: PoN/cnvkit_novaseq_13.cnn
     url: https://figshare.com/ndownloader/files/40914854?private_link=430129261fe3d472485b

 cnvkit_batch_hrd:
   normal_reference_hrd:
      checksum: e7853030e7a6b0ccbeffb7c008983a29
      path: PoN/cnvkit_novaseq_13_HRD.cnn
      url: https://figshare.com/ndownloader/files/40914854?private_link=430129261fe3d472485b

 msisensor_pro:
   PoN:
     checksum: 40bda778c9208a366b39ec0e6cefde11
     path: PoN/Msisensor_pro_reference_novaseq_13.list_baseline
     url: https://figshare.com/ndownloader/files/40882871?private_link=430129261fe3d472485b

 reference:
    background:
      checksum: 563aa06990d90ed3ef33b4da1aac3c2e
      path: Background/background_panel_novaseq_13_dp500_af015.tsv
      url: https://figshare.com/ndownloader/files/40882844?private_link=430129261fe3d472485b
    
    artifacts: 
      checksum: 6d589735a4b922a6f7e852539f44a539
      path: Artifact/artifact_panel_novaseq_13.tsv
      url: https://figshare.com/ndownloader/files/40882838?private_link=430129261fe3d472485b

