---
 svdb_query:
   db_string:
     checksum: 076f3a9bec5e9941eb4bbbf4594c0037
     path: GMS560/PoN/SVDB/all_TN_292_svdb_0.8_20220505.vcf
     type: file
     url: https://figshare.scilifelab.se/ndownloader/files/40882898

 purecn:
   extra: 
     checksum: eb311461a92b53a9494bba9625ecd4c3
     path: GMS560/PoN/purecn/mapping_bias_nextseq_27_hg19.rds
     type: file
     url: https://figshare.scilifelab.se/ndownloader/files/40882865

   normaldb:
     checksum: d77528e5bfeec40791235e52dcbed7ef
     path: GMS560/PoN/purecn/normalDB_nextseq_27_hg19.rds
     type: file
     url: https://figshare.scilifelab.se/ndownloader/files/40882874


 gatk_denoise_read_counts:
   normal_reference:
      checksum: ab0a2f3276125c8695b72a2b2c5779ea
      path: GMS560/PoN/gatk_cnv_novaseq_13.hdf5
      type: file
      url: https://figshare.scilifelab.se/ndownloader/files/40882862

 cnvkit_batch:
   normal_reference:
     checksum: 203d8e695b6324f8a5c27e2c7882f3d2
     path: GMS560/PoN/cnvkit_PoN_combined_hg19.cnn
     type: file
     url: https://figshare.com/ndownloader/files/46640134?private_link=88202740beb6fcbac09d

 cnvkit_batch_hrd:
   normal_reference_hrd:
      checksum: e7853030e7a6b0ccbeffb7c008983a29
      path: GMS560/PoN/cnvkit_novaseq_13_HRD.cnn
      type: file
      url: https://figshare.scilifelab.se/ndownloader/files/40914854

 jumble_run:
   normal_reference:
     checksum: 3add115d1471c3055d7984e3baea0364
     path: GMS560/PoN/jumble.combined.filtered.50.PoN.hg19.RDS
     type: file
     url: https://figshare.com/ndownloader/files/49365301?private_link=88202740beb6fcbac09d

 msisensor_pro_filter_sites:
   PoN:
     checksum: 40bda778c9208a366b39ec0e6cefde11
     path: GMS560/PoN/Msisensor_pro_reference_novaseq_13.list_baseline
     type: file
     url: https://figshare.scilifelab.se/ndownloader/files/40882871

 reference:
    background:
      checksum: 563aa06990d90ed3ef33b4da1aac3c2e
      path: GMS560/Background/background_panel_novaseq_13_dp500_af015.tsv
      type: file
      url: https://figshare.scilifelab.se/ndownloader/files/40882844
    
    artifacts: 
      checksum: 6d589735a4b922a6f7e852539f44a539
      path: GMS560/Artifact/artifact_panel_novaseq_13.tsv
      type: file
      url: https://figshare.scilifelab.se/ndownloader/files/40882838

