---

  arriba: 
    blacklist:
      checksum: ca7b0b42ec2498814a5c408a5477e052
      path: ref_data/arriba/blacklist_hg19_hs37d5_GRCh37_v2.3.0.tsv.gz
      type: file
      url: https://figshare.scilifelab.se/ndownloader/files/40928345
      
    extra1:
      checksum: b5bc63c70c9eb08c71528ee8b0186901
      path: ref_data/arriba/protein_domains_hg19_hs37d5_GRCh37_v2.3.0.gff3
      type: file
      url: https://figshare.scilifelab.se/ndownloader/files/40928354
   
    extra2:
      checksum: 2f063a0065c1c88d86c859b924d8d590
      path: ref_data/arriba/known_fusions_hg19_hs37d5_GRCh37_v2.3.0.tsv.gz
      type: file
      url: https://figshare.scilifelab.se/ndownloader/files/40928351
  
    gtf:
      checksum: 57b812f0595dc8a446ca81fe568e142d
      path: ref_data/gtf/hg19.refGene.gtf
      type: file
      url: https://figshare.scilifelab.se/ndownloader/files/42061200

    data_folder:
      compressed_checksum: 9d02d891cd4a0c912c0ea7c2a73135d3
      path: arriba_v2.3.0
      type: folder
      content_checksum:
        database/blacklist_hg19_hs37d5_GRCh37_v2.3.0.tsv.gz:ca7b0b42ec2498814a5c408a5477e052
        database/blacklist_hg38_GRCh38_v2.3.0.tsv.gz:8c6899e83e7509ed6b745f17667bd93a
        database/blacklist_mm10_GRCm38_v2.3.0.tsv.gz:9de54df12176c69e608356fb8d0e917d
        database/blacklist_mm39_GRCm39_v2.3.0.tsv.gz:833f2a9fe5e1905cb52b144c05202444
        database/CREDITS:dff9a468097dfc38595407e9eb79d0a1
        database/cytobands_hg19_hs37d5_GRCh37_v2.3.0.tsv:9333eaa96c56fa22624ab432b8391b2b
        database/cytobands_hg38_GRCh38_v2.3.0.tsv:7bd504feefb33fcfc9be0517439a423c
        database/cytobands_mm10_GRCm38_v2.3.0.tsv:117386b1fa0b46adbf39b6825e7f179b  
        database/cytobands_mm39_GRCm39_v2.3.0.tsv:79957259ca49eb0748c6a98ef77b6998
        database/known_fusions_hg19_hs37d5_GRCh37_v2.3.0.tsv.gz:2f063a0065c1c88d86c859b924d8d590
        database/known_fusions_hg38_GRCh38_v2.3.0.tsv.gz:2d6975f9c9379085d67f44cf45eac15f  
        database/known_fusions_mm10_GRCm38_v2.3.0.tsv.gz:fba82262f29b3836b75a075d6b953d0f  
        database/known_fusions_mm39_GRCm39_v2.3.0.tsv.gz:94ef2701883b34a9020c56a24854d94b
        database/protein_domains_hg19_hs37d5_GRCh37_v2.3.0.gff3:b5bc63c70c9eb08c71528ee8b0186901
        database/protein_domains_hg38_GRCh38_v2.3.0.gff3:43c387a784ebeed71b4147076cebf978
        database/protein_domains_mm10_GRCm38_v2.3.0.gff3:b7f40c14db3adade3e3cc0b432dc2525
        database/protein_domains_mm39_GRCm39_v2.3.0.gff3:196698d3e6877b0bc34a358e8d654394
        database/RefSeq_viral_genomes_v2.3.0.fa.gz:02f0cb5b3704c41be25deafe6a1d7578
      url: https://figshare.scilifelab.se/ndownloader/files/42116952

  arriba_draw_fusion:
    cytobands: 
      checksum: 9333eaa96c56fa22624ab432b8391b2b
      path: ref_data/arriba/cytobands_hg19_hs37d5_GRCh37_v2.3.0.tsv
      type: file
      url: https://figshare.scilifelab.se/ndownloader/files/40928348
   
    protein_domains: 
      checksum: b5bc63c70c9eb08c71528ee8b0186901
      path: ref_data/arriba/protein_domains_hg19_hs37d5_GRCh37_v2.3.0.gff3
      type: file
      url: https://figshare.scilifelab.se/ndownloader/files/40928354

  bwa:
   amb:
     checksum: b1998db7fbda653133fa278cd9b1e61b
     path: ref_data/hg19/hg19.with.mt.fasta.amb
     type: file
     url: https://figshare.scilifelab.se/ndownloader/files/42061203
   ann:
     checksum: 91ed3e11eb9d28cdfdd6cfd7977ef201
     path: ref_data/hg19/hg19.with.mt.fasta.ann
     type: file
     url: https://figshare.scilifelab.se/ndownloader/files/42061206
   bwt:
     checksum: da1a091388a038c22e1d5c555db00a8b
     path: ref_data/hg19/hg19.with.mt.fasta.bwt
     type: file
     url: https://figshare.scilifelab.se/ndownloader/files/42061209
   pac:
     checksum: 90c98011896647750981f091b90bf2af
     path: ref_data/hg19/hg19.with.mt.fasta.pac
     type: file
     url: https://figshare.scilifelab.se/ndownloader/files/42061221
   sa:
     checksum: 9acd60cb19c1dd8da83283348670c744
     path: ref_data/hg19/hg19.with.mt.fasta.sa
     type: file
     url: https://figshare.scilifelab.se/ndownloader/files/42061224

  fuseq_wes:
    reference:
      type: folder
      compressed_checksum: c66a0ba6fe5b76fedf16b404f67fcda4
      path: ref_data/fuseq_wes
      content_checksum:
        ensmbl_paralogs_grch37.RData: af95895660e6b09ca07ffcedcc6c7ef1
        Mitelman_fusiondb.RData: e4fbf81b5b02b9fe201161d324405822
        UCSC_hg19_wes_contigSize3000_bigLen130000_r100.json: 30d56f2305d33734e0bff3eb888b12ba
        UCSC_hg19_wes_contigSize3000_bigLen130000_r100.sqlite: 92357e04c72c06ab39b7cff59d24a852
      url: https://figshare.scilifelab.se/ndownloader/files/42116949

  gatk_get_pileup_summaries:
    sites:
      checksum: 1eb85e09195f0092e389510b40765f5e
      path: ref_data/GNOMAD/small_exac_common_3.hg19.vcf.gz
      type: file
      url: https://figshare.scilifelab.se/ndownloader/files/40933373

    variants:
      checksum: 1eb85e09195f0092e389510b40765f5e
      path: ref_data/GNOMAD/small_exac_common_3.hg19.vcf.gz
      type: file
      url: https://figshare.scilifelab.se/ndownloader/files/40933373

    variants_tbi:
      checksum: a52fae234aab2fb4f0d46963f7e6de09
      path: ref_data/GNOMAD/small_exac_common_3.hg19.vcf.gz.tbi
      type: file
      url: https://figshare.scilifelab.se/ndownloader/files/42061254
    
  gene_fuse:
    fasta:
      checksum: 7c1739fd43764bd5e3b9b76ce8635bf0
      path: ref_data/hg19/hg19.with.mt.fasta
      type: file
      url: https://figshare.scilifelab.se/ndownloader/files/42060171 
      
  references:
    fasta:
      checksum: 7c1739fd43764bd5e3b9b76ce8635bf0
      path: ref_data/hg19/hg19.with.mt.fasta
      type: file
      url: https://figshare.scilifelab.se/ndownloader/files/42060171 
      
    fai:
      checksum: 6071b578df509d097874b3e58a1a9fc6
      path: ref_data/hg19/hg19.with.mt.fasta.fai
      type: file
      url: https://figshare.scilifelab.se/ndownloader/files/42061218
    
    dict:
      checksum: bfd3a82e44e749f6864084ec51119a09
      path: ref_data/hg19/hg19.with.mt.fasta.dict
      type: file
      url: https://figshare.scilifelab.se/ndownloader/files/42061359

  fusioncatcher:
    genome_path:
      compressed_checksum: df21451c68b4ad9cb7f3cc0052c661c8,
      path: human_v102/ 
      type: file
      url:
        https://figshare.scilifelab.se/ndownloader/files/42061230:5f4968cf58a28bfe661ee3d1207259c6
        https://figshare.scilifelab.se/ndownloader/files/42061233:ad677c79617e36f85592b45918a10f21
        https://figshare.scilifelab.se/ndownloader/files/42061242:b4a57d1a48b12e3302fa7d12e6ac6347
        https://figshare.scilifelab.se/ndownloader/files/42061248:1280e3204b6990b825c762ac14e4446a
      
  star:
    genome_index:
      compressed_name: star_v2.7.10a_hg19_index.tar.gz
      path: star
      type: file
      url: https://figshare.scilifelab.se/ndownloader/files/42061278
      

  star-fusion:
    genome_path:
      #path: ref_data/ctat_genome_lib_build_dir
      path: GRCh37_gencode_v19_CTAT_lib_Mar012021.plug-n-play.tar.gz
      type: file
      url: https://figshare.scilifelab.se/ndownloader/files/42084318      
      #compressed_name: GRCh37_gencode_v19_CTAT_lib_Mar012021.plug-n-play.tar.gz

  vep:
    vep_cache:
      path: /sw/data/vep/107
      type: folder
      

