---

  arriba: 
    blacklist:
      checksum: ca7b0b42ec2498814a5c408a5477e052
      path: ref_data/arriba/blacklist_hg19_hs37d5_GRCh37_v2.3.0.tsv.gz
      url: https://figshare.com/ndownloader/files/40928345?private_link=f0837fafe533b970fd02
      
    extra1:
      checksum: b5bc63c70c9eb08c71528ee8b0186901
      path: ref_data/arriba/protein_domains_hg19_hs37d5_GRCh37_v2.3.0.gff3
      url: https://figshare.com/ndownloader/files/40928354?private_link=f0837fafe533b970fd02
   
    extra2:
      checksum: 2f063a0065c1c88d86c859b924d8d590
      path: ref_data/arriba/known_fusions_hg19_hs37d5_GRCh37_v2.3.0.tsv.gz
      url: https://figshare.com/ndownloader/files/40928351?private_link=f0837fafe533b970fd02
  
    gtf:
      checksum: 57b812f0595dc8a446ca81fe568e142d
      path: ref_data/gtf/hg19.refGene.gtf
      #url: 57b812f0595dc8a446ca81fe568e142d

  arriba_draw_fusion:
    cytobands: 
      checksum: 9333eaa96c56fa22624ab432b8391b2b
      path: ref_data/arriba/cytobands_hg19_hs37d5_GRCh37_v2.3.0.tsv
      url: https://figshare.com/ndownloader/files/40928348?private_link=f0837fafe533b970fd02
   
    protein_domains: 
      checksum: b5bc63c70c9eb08c71528ee8b0186901
      path: ref_data/arriba/protein_domains_hg19_hs37d5_GRCh37_v2.3.0.gff3
      url: https://figshare.com/ndownloader/files/40928354?private_link=f0837fafe533b970fd02

  bwa:
   amp:
     checksum: b1998db7fbda653133fa278cd9b1e61b
     path: ref_data/hg19/hg19.with.mt.fasta.amb
#    url:
   ann:
     checksum: 745e9a6afe1951cc54e8cc1b6c1429ff
     path: ref_data/hg19/hg19.with.mt.fasta.ann
#    url:
   bwt:
     checksum: da1a091388a038c22e1d5c555db00a8b
     path: ref_data/hg19/hg19.with.mt.fasta.bwt
#    url:
   pac:
     checksum: 90c98011896647750981f091b90bf2af
     path: ref_data/hg19/hg19.with.mt.fasta.pac
#    url:
   sa:
     checksum: 9acd60cb19c1dd8da83283348670c744
     path: ref_data/hg19/hg19.with.mt.fasta.sa
#    url:

  fuseq_wes:
   ref_json:
     checksum: 30d56f2305d33734e0bff3eb888b12ba
     path: ref_data/fuseq_wes/UCSC_hg19_wes_contigSize3000_bigLen130000_r100.json
     url: https://figshare.com/ndownloader/files/40933238?private_link=cac83963374a4c0407a5

   gtfSqlite: 
     checksum: 92357e04c72c06ab39b7cff59d24a852 
     path: ref_data/fuseq_wes/UCSC_hg19_wes_contigSize3000_bigLen130000_r100.sqlite
     url: https://figshare.com/ndownloader/files/40933241?private_link=cac83963374a4c0407a5

   fusiondb:
     checksum: e4fbf81b5b02b9fe201161d324405822
     path: ref_data/fuseq_wes/Mitelman_fusiondb.RData
     url: https://figshare.com/ndownloader/files/40933235?private_link=cac83963374a4c0407a5

   paralogdb:
     checksum: af95895660e6b09ca07ffcedcc6c7ef1
     path: ref_data/fuseq_wes/ensmbl_paralogs_grch37.RData
     url: https://figshare.com/ndownloader/files/40933232?private_link=cac83963374a4c0407a5

  gatk_get_pileup_summaries:
    sites:
      checksum: 1eb85e09195f0092e389510b40765f5e
      path: ref_data/GNOMAD/small_exac_common_3.hg19.vcf.gz
      url: https://figshare.com/ndownloader/files/40933373?private_link=1b151eaf283e62084f0f

    variants:
      checksum: 1eb85e09195f0092e389510b40765f5e
      path: ref_data/GNOMAD/small_exac_common_3.hg19.vcf.gz
      url: https://figshare.com/ndownloader/files/40933373?private_link=1b151eaf283e62084f0f

    variants_tbi:
      checksum: 7d5a3f6d3350476a234aed9953351a08
      path: ref_data/GNOMAD/small_exac_common_3.hg19.vcf.gz.tbi
      url: https://figshare.com/ndownloader/files/41119760?private_link=1b151eaf283e62084f0f
    
  gene_fuse:
    fasta:
      checksum: 7c1739fd43764bd5e3b9b76ce8635bf0
      path: ref_data/hg19/hg19.with.mt.fasta
#     url: 
      
  references:
    fasta:
      checksum: 7c1739fd43764bd5e3b9b76ce8635bf0
      path: ref_data/hg19/hg19.with.mt.fasta
#      url:
      
    fai:
      checksum: 6071b578df509d097874b3e58a1a9fc6
      path: ref_data/hg19/hg19.with.mt.fasta.fai
#     url:
    
    dict:
      checksum: bfd3a82e44e749f6864084ec51119a09
      path: ref_data/hg19/hg19.with.mt.fasta.dict

