site_name: Twist Solid
nav:
  - Overview:
      - Introduction: index.md
      - Pipeline overview: overview.md
      - Result files: result_files.md
      - Running the pipeline: running.md
      - Pipeline setup and cofiguration: setup.md
      - Reference files: references.md
  - DNA Pipeline:
    - Prealignment: dna_prealignment.md
    - Alignment: dna_alignment.md
    - SNV and INDELs: dna_snv_indels.md
    - CNVs: dna_cnvs.md
    - Fusions: dna_fusions.md
    - Biomarkers: dna_biomarkers.md
    - QC: dna_qc.md
  - RNA Pipeline:
    - Fusions: rna_fusions.md
    - Exon skipping: rna_exon_skipping.md
    - ID-SNPs: rna_id_snps.md
    - QC: rna_qc.md
  - Project Info:
    - Changelog: changelog.md
    - Citations: citations.md
    - Contributing: contributing.md
    - Credits: credits.md
    - Frequently Asked Questions: faq.md
    - License: license.md
    - More Resources: more_resources.md


theme: readthedocs
extra_css: [extra.css]
markdown_extensions:
  - abbr
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
      base_path: ["docs"]
  - mdx_spanner
# plugins:
#   - search
#   - mkdocs-simple-hooks:
#       hooks:
#         on_pre_build: "docs.hooks:copy_changelog_and_license"
#  - schema_reader:
#      include:
#        - "./workflow/schemas"
