filters:
  vaf:
    description: "Hard filter variants with low vaf (AF lower than 0.05)"
    expression: "(FORMAT:AF:0 < 0.05)"
    soft_filter: "False"
  ad:
    description: "Hard filter variants with few observations (AD lower than 20)"
    expression: "FORMAT:AD:1 < 20"
    soft_filter: "False"
  snp_type:
    description: "Hard filter variants that are not SNVs"
    expression: "(!exist[SNV, VEP:VARIANT_CLASS])"
    soft_filter: "False"
