
reference:
  background: ""
  artifacts: ""
  fasta: "/data/ref_genomes/GRCh38_p14/homo_sapiens.fasta"
  fasta_rna: "/data/ref_data/star-fusion/GRCh38_gencode_v37_CTAT_lib_Mar012021.plug-n-play/ctat_genome_lib_build_dir/ref_genome.fa"
  dict: "/data/ref_genomes/GRCh38_p14/homo_sapiens.fasta.dict"
  fai: "/data/ref_genomes/GRCh38_p14/homo_sapiens.fasta.fai"
  design_bed: ""
  design_intervals: ""
  design_intervals_gatk_cnv: ""
  design_bed_rna: "/projects/wp1/nobackup/ngs/utveckling/Twist_RNA_DATA/bed/Twist_RNA_Design5.annotated.bed"
  design_intervals_rna: "/projects/wp1/nobackup/ngs/utveckling/Twist_RNA_DATA/bed/Twist_RNA_Design5.annotated.20230630.interval_list"
  skip_chrs:
    - "chrM"

arriba:
  assembly: "/data/ref_genomes/GRCh38_p14/homo_sapiens.fasta"
  blacklist: "/data/ref_data/arriba/arriba_v2.3.0/database/blacklist_hg38_GRCh38_v2.3.0.tsv.gz"
  gtf: "/data/ref_genomes/GRCh38/gtf/hg38.refGene.gtf"
  extra: "-p /data/ref_data/arriba/arriba_v2.3.0/database/protein_domains_hg38_GRCh38_v2.3.0.gff3 -k /data/ref_data/arriba/arriba_v2.3.0/database/known_fusions_hg38_GRCh38_v2.3.0.tsv.gz"

arriba_draw_fusion:
  cytobands: "/data/ref_data/arriba/arriba_v2.3.0/database/cytobands_hg38_GRCh38_v2.3.0.tsv"
  gtf: "/data/ref_genomes/GRCh38/gtf/hg38.refGene.gtf"
  protein_domains: "/data/ref_data/arriba/arriba_v2.3.0/database/protein_domains_hg38_GRCh38_v2.3.0.gff3"

annotate_cnv:
  cnv_amp_genes: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/cnv_amp_genes.bed"
  cnv_loh_genes_validated: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/cnv_loh_uppsala_genes.bed"
  cnv_loh_genes_all: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/cnv_loh_genes.bed"


bcftools_annotate:
  annotation_db: "/data/ref_genomes/GNOMAD/small_exac_common_3.hg38.vcf.gz"
  
bcftools_filter_include_region:
  exon: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/pool1_pool2.sort.merged.padded20.cnv200.hg19.split_fusion_genes.MUC6_31_rm.exon_only.reannotated.230222.bed"

bcftools_filter_exclude_region:
  blacklist: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/cnvkit_germline_blacklist_20221221.bed"

bcftools_id_snps:
  snps_bed: "/projects/wp1/nobackup/ngs/utveckling/Twist_RNA_DATA/bed/ID_SNPs.bed"

bwa_mem:
  amb: "/data/ref_genomes/GRCh38_p14/homo_sapiens.fasta.amb"
  ann: "/data/ref_genomes/GRCh38_p14/homo_sapiens.fasta.ann"
  bwt: "/data/ref_genomes/GRCh38_p14/homo_sapiens.fasta.bwt"
  pac: "/data/ref_genomes/GRCh38_p14/homo_sapiens.fasta.pac"
  sa: "/data/ref_genomes/GRCh38_p14/homo_sapiens.fasta.sa"

call_small_cnv_deletions:
  regions_file: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/cnv_deletion_genes.tsv"

call_small_cnv_amplifications:
  regions_file: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/cnv_amplification_genes.tsv"

cnvkit_batch:
  normal_reference: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/PoN/cnvkit_nextseq_36.cnn"

cnvkit_batch_hrd:
  normal_reference_hrd: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/PoN/cnvkit_nextseq_27_HRD.cnn"

exon_skipping:
  design_bed: "/projects/wp1/nobackup/ngs/utveckling/Twist_RNA_DATA/bed/Twist_RNA_Design5.annotated.bed"


filter_fuseq_wes:
  gene_white_list: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA_HG38/fuseq_wes/fuseq_wes_gene_white_list.txt"
  transcript_black_list: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA_HG38/fuseq_wes/fuseq_wes_transcript_black_list.txt"
  gtf: "/data/ref_genomes/GRCh38/gtf/hg38.refGene.gtf"

fuseq_wes:
  ref_json: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA_HG38/fuseq_wes/UCSC_hg38_wes_contigSize3000_bigLen130000_r100.json"
  gtfSqlite: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA_HG38/fuseq_wes/UCSC_hg38_wes_contigSize3000_bigLen130000_r100.sqlite"
  fusiondb: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA_HG38/fuseq_wes/Mitelman_fusiondb.RData"
  paralogdb: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA_HG38/fuseq_wes/ensmbl_paralogs_grch38.RData"
  params: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/fuseq_wes/fuseq_params.txt"

fusioncatcher:
  genome_path: "/data/ref_data/fusioncatcher/human_v102/human_v102/"


gatk_collect_allelic_counts:
  SNP_interval: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA_HG38/bed/gnomad_SNP_0.001_target.annotated.hg38.interval_list"

gatk_denoise_read_counts:
  normal_reference: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/PoN/gatk_cnv_nextseq_36.hdf5"


gatk_get_pileup_summaries:
  sites: "/data/ref_genomes/GNOMAD/small_exac_common_3.hg38.vcf.gz"
  variants: "/data/ref_genomes/GNOMAD/small_exac_common_3.hg38.vcf.gz"


gene_fuse:
  genes: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/gene_fuse/GMS560_fusion_w_pool2.hg38.csv"
  fasta: "/data/ref_genomes/GRCh38_p14/homo_sapiens.fasta"

hotspot_annotation:
  hotspots: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/Hotspots_combined_regions_nodups.csv"
  chr_translation_file: "config/hotspot_report.chr.translation.hg38"

hotspot_info:
  hotspot_mutations: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/Hotspots_combined_regions_nodups.csv"

hotspot_report:
  hotspot_mutations: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/Hotspots_combined_regions_nodups.csv"
  report_config: "config/hotspot_report.yaml"
  chr_translation_file: "config/hotspot_report.chr.translation.hg38"
  levels:
    - [200, "ok", "yes"]
    - [30, "low", "yes"]
    - [0, "low", "not analyzable"]

manta_config_t:
  extra: "--exome --callRegions /projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/pool1_pool2.sort.merged.padded20.cnv200.hg19.split_fusion_genes.210608.bed.gz"


merge_cnv_json:
  annotations:
    - /projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/cnv_amp_genes.bed
    - /projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/cnv_loh_genes.bed
  filtered_cnv_vcfs:
    - cnv_sv/svdb_query/{sample}_{type}.{tc_method}.svdb_query.annotate_cnv.cnv_amp_genes.filter.cnv_hard_filter_amp.vcf.gz
    - cnv_sv/svdb_query/{sample}_{type}.{tc_method}.svdb_query.annotate_cnv.cnv_loh_genes_all.filter.cnv_hard_filter_loh.vcf.gz
  unfiltered_cnv_vcfs:
    - cnv_sv/svdb_query/{sample}_{type}.{tc_method}.svdb_query.annotate_cnv.cnv_amp_genes.vcf.gz
    - cnv_sv/svdb_query/{sample}_{type}.{tc_method}.svdb_query.annotate_cnv.cnv_loh_genes_all.vcf.gz
  germline_vcf: snv_indels/bcbio_variation_recall_ensemble/{sample}_{type}.ensembled.vep_annotated.filter.germline.exclude.blacklist.vcf.gz


msisensor_pro:
  PoN: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/PoN/Msisensor_pro_reference_nextseq_36.list_baseline"


purecn:
  genome: "hg38"
  interval_padding: 100
  segmentation_method: "internal"
  fun_segmentation: "PSCBS"
  extra: "--model betabin --mapping-bias-file /projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/purecn/mapping_bias_nextseq_27_hg19.rds"
  normaldb: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/purecn/normalDB_nextseq_27_hg19.rds"
  intervals: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/purecn/targets_twist-gms-st_hg19_25000_intervals.txt"

purecn_coverage:
  intervals: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/purecn/targets_twist-gms-st_hg19_25000_intervals.txt"

report_fusions:
  annotation_bed: "/projects/wp1/nobackup/ngs/utveckling/Twist_RNA_DATA/bed/Twist_RNA_fusionpartners.bed"
  fp_fusions: "/projects/wp1/nobackup/ngs/utveckling/Twist_RNA_DATA/bed/filter_rna_fusions_20231020.txt"

report_gene_fuse:
  filter_fusions: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/gene_fuse/filter_fusions_20230214.csv"


scarhrd:
  reference_name: "grch38"

star:
  genome_index: "/data/ref_data/star/v2.7.10a_hg38/"
  extra: "--quantMode GeneCounts --sjdbGTFfile /data/ref_genomes/GRCh38/gtf/hg38.refGene.gtf --outSAMtype BAM SortedByCoordinate --chimSegmentMin 10 --chimOutType WithinBAM SoftClip --chimJunctionOverhangMin 10 --chimScoreMin 1 --chimScoreDropMax 30 --chimScoreJunctionNonGTAG 0 --chimScoreSeparation 1 --alignSJstitchMismatchNmax 5 -1 5 5 --chimSegmentReadGapMax 3"

star_fusion:
  genome_path: "/data/ref_data/star-fusion/GRCh38_gencode_v37_CTAT_lib_Mar012021.plug-n-play/ctat_genome_lib_build_dir/"
  

svdb_query:
  db_string: "--db /projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/SVDB/all_TN_292_svdb_0.8_20220505.vcf --out_frq Twist_AF --out_occ Twist_OCC"

vep:
  vep_cache:  "/data/ref_genomes/VEP/"
  mode: --offline --cache
  extra: " --assembly GRCh38 --check_existing --pick --sift b --polyphen b --ccds --uniprot --hgvs --symbol --numbers --domains --regulatory --canonical --protein --biotype --uniprot --tsl --appris --gene_phenotype --af --af_1kg --af_gnomad --max_af --pubmed --variant_class "
