filters:
  intron:
    description: "Hard filter intronic variants"
    expression: "(exist[intron_variant, VEP:Consequence] and !exist[splice, VEP:Consequence] and VEP:SYMBOL != MET and VEP:SYMBOL != TERT and !exist[COSV[0-9]+, VEP:Existing_variation])"
    soft_filter: "False"
  artifacts:
    description: "Hard filter variants found in more than 3 normal samples"
    expression: "((INFO:Artifact:0 > 3 and INFO:ArtifactNrSD:0 < 10) or (INFO:Artifact:1 > 3 and INFO:ArtifactNrSD:1 < 10))"
    soft_filter: "False"
  background:
    description: "Hard filter position where background distribution overlaps variant (lower than 4 SD from median)"
    expression: "(INFO:PositionNrSD < 0 and !exist[1-hotspot, INFO:Hotspot])"
    soft_filter: "False"
  germline:
    description: "Hard filter germline"
    expression: "(VEP:gnomAD_AF > 0.005)"
    soft_filter: "False"
  af_ad_snv1:
    description: "Hard filter SNV variants with low vaf and low ad"
    expression: "(FORMAT:AF:0 < 0.003 and exist[SNV, VEP:VARIANT_CLASS])"
    soft_filter: "False"
  af_ad_snv2:
    description: "Hard filter SNV variants with low vaf and low ad"
    expression: "(FORMAT:AF:0 < 0.004 and FORMAT:AD:1 < 11 and exist[SNV, VEP:VARIANT_CLASS])"
    soft_filter: "False"
  af_ad_snv3:
    description: "Hard filter SNV variants with low vaf and low ad"
    expression: "(FORMAT:AF:0 < 0.005 and FORMAT:AD:1 < 9 and exist[SNV, VEP:VARIANT_CLASS])"
    soft_filter: "False"
  af_ad_snv4:
    description: "Hard filter SNV variants with low vaf and low ad"
    expression: "(FORMAT:AF:0 < 0.006 and FORMAT:AD:1 < 7 and exist[SNV, VEP:VARIANT_CLASS])"
    soft_filter: "False"
  af_ad_snv5:
    description: "Hard filter SNV variants with low vaf and low ad"
    expression: "(FORMAT:AD:1 < 5 and !exist[SNV, VEP:VARIANT_CLASS])"
    soft_filter: "False"
  af_ad_indel1:
    description: "Hard filter INDEL variants with low vaf and low ad"
    expression: "(FORMAT:AF:0 < 0.005"
    soft_filter: "False"
  af_ad_indel2:
    description: "Hard filter INDEL variants with low vaf and low ad"
    expression: "(FORMAT:AF:0 < 0.008 and FORMAT:AD:1 < 14 and !exist[SNV, VEP:VARIANT_CLASS])"
    soft_filter: "False"
  af_ad_indel3:
    description: "Hard filter INDEL variants with low vaf and low ad"
    expression: "(FORMAT:AD:1 < 5 and !exist[SNV, VEP:VARIANT_CLASS])"
    soft_filter: "False"