resources: "config/resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.0.1"

trimmer_software: "fastp"

reference:
  background: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/Background/background_panel_26_normal.tsv"
  artifacts: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/Artifact/artifact_panel_26_normal.tsv"
  fasta: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.fasta"
  dict: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.dict"
  amb: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.amb"
  ann: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.ann"
  bwt: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.bwt"
  fai: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.fai"
  pac: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.pac"
  sa: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.sa"
  design_bed: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/pool1_pool2_nochr_3c.sort.merged.padded20.hg19.210311.met.annotated.bed"
  design_intervals: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/pool1_pool2_nochr_3c.sort.merged.padded20.hg19.210311.met.annotated.interval_list"
  design_intervals_gatk_cnv: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/pool1_pool2_nochr_3c.sort.merged.padded20.hg19.210311.met.annotated.bed.preprocessed.interval_list"
  hotspots: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/Hotspots_combined.csv"
  svdb_vcf: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/SVDB/normal_26_svdb_0.8.vcf"
  skip_chrs:
    - "chrM"


bwa_mem:
  container: "docker://hydragenetics/bwa_mem:0.7.17"
  extra: "-R '@RG\\tID:{sample}\\tSM:{sample}\\tPL:illumina\\tPU:{sample}' -v 1 "

mark_duplicates:
  container: "docker://hydragenetics/picard:2.25.0"

samtools_index:
  container: "docker://hydragenetics/common:0.0.1"

merge_bam:
  container: "docker://hydragenetics/common:0.0.1"

fastp_pe:
  container: "docker://hydragenetics/fastp:0.20.1"

vardict:
  container: "docker://gmsuppsala/somatic:develop"
  bed_columns: "-c 1 -S 2 -E 3 -g 4"
  allele_frequency_threshold: "0.01"

mutect2:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

mutect2_gvcf:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

merge_vcf:
  container: "docker://hydragenetics/common:0.0.1"

merge_gvcf:
  container: "docker://hydragenetics/common:0.0.1"

bgzip_vcf:
  container: "docker://hydragenetics/common:0.0.1"

tabix_vcf:
  container: "docker://hydragenetics/common:0.0.1"

decompose:
  container: "docker://gmsuppsala/somatic:develop"

normalize:
  container: "docker://gmsuppsala/somatic:develop"

sort_vcf:
  container: "docker://hydragenetics/common:0.0.1"

ensemble_vcf:
  container: "docker://gmsuppsala/somatic:develop"
  callers:
    - vardict
    - mutect2
  sort_order: "vardict,mutect2"

fix_af:
  container: "docker://hydragenetics/common:0.0.1"

freebayes:
  container: "docker://gmsuppsala/somatic:develop"

bed_split:
  container: "docker://hydragenetics/common:0.0.1"

vep:
  container: "docker://hydragenetics/vep:105"
  vep_cache:  "/data/ref_genomes/VEP/"
  mode: --offline --cache
  extra: " --check_existing --pick --sift b --polyphen b --ccds --uniprot --hgvs --symbol --numbers --domains --regulatory --canonical --protein --biotype --uniprot --tsl --appris --gene_phenotype --af --af_1kg --af_gnomad --max_af --pubmed --variant_class "

calculate_seqrun_background:
  container: "docker://python:3.9.7-slim"

bgzip_vcf:
  container: "docker://hydragenetics/common:0.0.1"

tabix_vcf:
  container: "docker://hydragenetics/common:0.0.1"

fastqc:
  container: "docker://hydragenetics/fastqc:0.11.9"

samtools_stats:
  container: "docker://hydragenetics/common:0.0.1"

picard_alignment_summary_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_duplication_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_hs_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_insert_size:
  container: "docker://hydragenetics/picard:2.25.0"

hotspot_info:
  container: "docker://hydragenetics/common:0.0.1"

msisensor_pro:
  container: "docker://hydragenetics/msisensor_pro:1.1.a"
  PoN: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/PoN/Msisensor_pro_reference_26_normal.list_baseline"

tmb:
  container: "docker://hydragenetics/common:0.0.1"

hrd:
  container: "docker://hydragenetics/common:0.0.1"

gene_fuse:
  container: "docker://hydragenetics/genefuse:0.6.1"
  genes: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/gene_fuse/druggable.hg19.csv"

cnvkit_call:
  container: "docker://gmsuppsala/somatic:develop"
  normal_reference: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/PoN/cnvkit_26_normal.PoN.cnn"

cnvkit_call_loh:
  container: "docker://gmsuppsala/somatic:develop"

cnvkit_scatter:
  container: "docker://gmsuppsala/somatic:develop"

cnvkit_vcf:
  container: "docker://hydragenetics/common:0.0.1"

germline_vcf:
  container: "docker://ensemblorg/ensembl-vep:release_99.0"

gatk_cnv_collect_read_counts:
  container: "docker://gmsuppsala/somatic:develop"

gatk_cnv_denoise_read_counts:
  container: "docker://gmsuppsala/somatic:develop"
  normal_reference: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/PoN/gatk_cnv_26_normal.hdf5"

gatk_cnv_collect_allelic_counts:
  container: "docker://gmsuppsala/somatic:develop"
  SNP_interval: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/gnomad_SNP_0.001_target.annotated.interval_list"

gatk_cnv_model_segments:
  container: "docker://gmsuppsala/somatic:develop"

gatk_cnv_call_copy_ratio_segments:
  container: "docker://gmsuppsala/somatic:develop"

gatk_cnv_vcf:
  container: "docker://hydragenetics/common:0.0.1"

svdb_merge:
  container: "docker://hydragenetics/svdb:2.5.0"
  cnv_callers:
    - "cnvkit"
    - "gatk_cnv"

svdb_query:
  container: "docker://hydragenetics/svdb:2.5.0"

multiqc:
  container: "docker://hydragenetics/multiqc:1.11"
  config: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/multiqc_config.yaml"
  qc_files:
    - "qc/picard_hs_metrics/{sample}_{type}.HsMetrics.txt"
    - "qc/picard_alignment_summary_metrics/{sample}_{type}.alignment_summary_metrics.txt"
    - "qc/fastqc/{sample}_{type}_fastq1_fastqc.zip"
    - "qc/fastqc/{sample}_{type}_fastq2_fastqc.zip"
    - "qc/picard_duplication_metrics/{sample}_{type}.duplication_metrics.txt"
    - "qc/samtools_stats/{sample}_{type}.samtools-stats.txt"
