filters:
  intron:
    description: "Hard filter intronic variants"
    expression: "(exist[intron_variant, VEP:Consequence] and !exist[splice, VEP:Consequence] and VEP:SYMBOL != MET and VEP:SYMBOL != TERT and !exist[COSV[0-9]+, VEP:Existing_variation])"
    soft_filter: "False"
  vaf:
    description: "Hard filter variants with low vaf (AF lower than 0.003)"
    expression: "(FORMAT:AF:0 < 0.003)"
    soft_filter: "False"
  artifacts:
    description: "Hard filter variants found in more than 3 normal samples"
    expression: "((INFO:Artifact:0 > 3 and INFO:ArtifactNrSD:0 < 10) or (INFO:Artifact:1 > 3 and INFO:ArtifactNrSD:1 < 10))"
    soft_filter: "False"
  background:
    description: "Hard filter position with where background distribution overlaps variant (lower than 4 SD from median)"
    expression: "(INFO:PositionNrSD < 0 and !exist[1-hotspot, INFO:Hotspot])"
    soft_filter: "False"
  germline:
    description: "Hard filter germline"
    expression: "(VEP:gnomAD_AF > 0.005)"
    soft_filter: "False"
  ad:
    description: "Hard filter variants with few observations (AD lower than 4)"
    expression: "(FORMAT:AD:1 < 4 and !exist[1-hotspot, INFO:Hotspot] and VEP:SYMBOL != TERT)"
    soft_filter: "False"
  ad_hotspot:
    description: "Hard filter hotspot variants with few observations (AD lower than 10)"
    expression: "(FORMAT:AD:1 < 4 and exist[1-hotspot, INFO:Hotspot] and VEP:SYMBOL != TERT)"
    soft_filter: "False"
  ad_TERT:
    description: "Hard filter TERT variants with few observations (AD lower than 4)"
    expression: "(FORMAT:AD:1 < 4 and VEP:SYMBOL = TERT)"
    soft_filter: "False"
