output: "../../config/output_files.yaml"

annotate_cnv:
  cnv_amp_genes: "reference/cnv_amp_genes.bed"
  cnv_del_genes: "reference/cnv_loh_genes.bed"

arriba:
  assembly: "reference/WASH7P.fna"
  blacklist: "reference/blacklist_hg19_hs37d5_GRCh37_v2.3.0.tsv.gz"
  gtf: "reference/hg19.refGene.gtf"
  extra: "-p reference/protein_domains_hg19_hs37d5_GRCh37_v2.3.0.gff3 -k reference/known_fusions_hg19_hs37d5_GRCh37_v2.3.0.tsv.gz"

arriba_draw_fusion:
  cytobands: "reference/cytobands_hg19_hs37d5_GRCh37_v2.3.0.tsv"
  gtf: "reference/WASH7P.gtf"
  protein_domains: "reference/protein_domains_hg19_hs37d5_GRCh37_v2.3.0.gff3"

bcftools_filter_include_region:
  exon: "DATA/design.noexon1.bed"
  nocnv: "DATA/design.noexon1.bed"

bcftools_filter_exclude_region:
  exon: "DATA/design.noexon1.bed"
  nocnv: "DATA/design.noexon1.bed"
  blacklist: "DATA/cnvkit_germline_blacklist_20221221.bed"

bcftools_id_snps:
  snps_bed: "DATA/ID_SNPs.bed"

bwa_mem:
  amb: "reference/WASH7P.fna.amb"
  ann: "reference/WASH7P.fna.ann"
  bwt: "reference/WASH7P.fna.bwt"
  pac: "reference/WASH7P.fna.pac"
  sa: "reference/WASH7P.fna.sa"

call_small_cnv_deletions:
  regions_file: "DATA/cnv_deletion_genes.tsv"

call_small_cnv_amplifications:
  regions_file: "DATA/cnv_amplification_genes.tsv"


cnvkit_batch:
  normal_reference: "DATA/design.PoN.cnn"
  method: "hybrid"

cnvkit_batch_hrd:
  normal_reference_hrd: "DATA/design.PoN.cnn"

cnv_html_report:
  template_dir: "../../config/cnv_report_template"


exon_skipping:
  design_bed: "reference/Twist_RNA_Design5.annotated.bed"


filter_fuseq_wes:
  gene_white_list: "reference/fuseq_wes_gene_white_list.txt"
  gtf: "reference/hg19.refGene.gtf"

fuseq_wes:
  ref_json: "reference/UCSC_hg19_wes_contigSize3000_bigLen130000_r100.json"
  gtfSqlite: "reference/UCSC_hg19_wes_contigSize3000_bigLen130000_r100.sqlite"
  fusiondb: "reference/Mitelman_fusiondb.RData"
  paralogdb: "reference/ensmbl_paralogs_grch37.RData"
  params: "reference/fuseq_params.txt"

filter_vcf:
  snv_soft_filter: "../../config/config_soft_filter_uppsala.yaml"
  snv_hard_filter: "../../config/config_hard_filter_uppsala.yaml"
  snv_hard_filter_purecn: "../../config/config_hard_filter_purecn.yaml"
  cnv_hard_filter_amp: "../../config/config_hard_filter_cnv_amp.yaml"
  cnv_hard_filter_loh: "../../config/config_hard_filter_cnv_loh.yaml"
  germline: "../../config/config_hard_filter_germline.yaml"

fusioncatcher:
  genome_path: "reference/human_v102/"

gatk_collect_allelic_counts:
  SNP_interval: "DATA/gnomad_SNP_0.001_target.annotated.interval_list"

gatk_denoise_read_counts:
  normal_reference: "DATA/gatk_cnv_nextseq_36.hdf5"

gatk_get_pileup_summaries:
  sites: "DATA/chr1_small_exac_common_3.hg19.vcf"
  variants: "DATA/chr1_small_exac_common_3.hg19.vcf"

gene_fuse:
  genes: "DATA/druggable.expanded.hg19.csv"
  fasta: "reference/WASH7P.fna"

hotspot_annotation:
  hotspots: "DATA/Hotspots_combined.csv"
  chr_translation_file: "../../config/hotspot_report.chr.translation.hg19"

hotspot_report:
  report_config: "../../config/config/hotspot_report.yaml"
  chr_translation_file: "../../config/hotspot_report.chr.translation.hg19"

msisensor_pro:
  PoN: "DATA/msisensor_pro_reference_26_normal.list_baseline"

multiqc:
  reports:
    DNA:
      config: "../../config/multiqc_config.yaml"
    RNA:
      config: "../../config/multiqc_config.yaml"

purecn_coverage:
  intervals: "reference/purecn_dummy_intervals.txt"

reference:
  artifacts: "DATA/artifact_panel_normal.tsv"
  background: "DATA/artifact_panel_normal.tsv"
  design_bed: "DATA/design.bed"
  design_intervals_gatk_cnv: "DATA/design.interval_list"
  design_intervals: "DATA/design.interval_list"
  design_bed_rna: "reference/Twist_RNA_Design5.annotated.bed"
  design_intervals_rna: "reference/Twist_RNA_Design5.annotated.interval_list"
  fasta: "reference/WASH7P.fna"
  fai: "reference/WASH7P.fna.fai"
  dict: "reference/WASH7P.dict"
  fasta_rna: "reference/WASH7P.fna"
  mappability: DATA/access-5k-mappable.bed

report_fusions:
  annotation_bed: "reference/Twist_RNA_fusionpartners.bed"

report_gene_fuse:
  filter_fusions: "reference/filter_fusions.csv"

star:
  container: "docker://hydragenetics/star:2.7.10a"
  genome_index: "reference_star_fusion/star_idx/"

star_fusion:
  container: "docker://hydragenetics/star-fusion:1.10.1"
  genome_path: "reference_star_fusion/"

vep:
  container: "docker://hydragenetics/vep:105"
  vep_cache:  "DATA/VEP/homo_sapiens/"
  