resources: "config/bianca/resources.yaml"
singularity_schema: "config/bianca/singularity.schema.yaml"

hydra_local_path: "PATH_TO_REPO"

reference:
  fasta_rna: "/sw/data/CTAT_RESOURCE_LIB/2021-03/GRCh37_gencode_v19_CTAT_lib_Mar012021.plug-n-play/ctat_genome_lib_build_dir/ref_genome.fa"


fusioncatcher:
  genome_path: "/sw/bioinfo/FusionCatcher/1.33/bianca/fusioncatcher/data/human_v102/"

gatk_collect_allelic_counts:
  SNP_interval: "/PROJECT_DATA/cnv/gnomad_SNP_0.001_target.annotated.interval_list"

gatk_denoise_read_counts:
  normal_reference: "/PROJECT_DATA/PoN/gatk_cnv_nextseq_36.hdf5"

gatk_get_pileup_summaries:
  sites: "/PROJECT_DATA/ref_data/GNOMAD/small_exac_common_3.hg19.vcf.gz"
  variants: "/PROJECT_DATA/ref_data/GNOMAD/small_exac_common_3.hg19.vcf.gz"

gene_fuse:
  genes: "/PROJECT_DATA/gene_fuse/GMS560_fusion_w_pool2.hg19.221117.csv"
  fasta: "/PROJECT_DATA/ref_data/hg19/hg19.with.mt.fasta"

filter_vcf:
  snv_soft_filter: "config/filters/config_soft_filter_uppsala_vep107.yaml"
  snv_hard_filter: "config/filters/config_hard_filter_uppsala_vep107.yaml"
  germline: "config/filters/config_hard_filter_germline_vep107.yaml"

hotspot_annotation:
  hotspots: "/PROJECT_DATA/design/Hotspots_combined_regions_nodups.csv"

hotspot_info:
  hotspot_mutations: "/PROJECT_DATA/design/Hotspots_combined_regions_nodups.csv"

hotspot_report:
  hotspot_mutations: "/PROJECT_DATA/design/Hotspots_combined_regions_nodups.csv"

manta_config_t:
  extra: "--exome --callRegions /PROJECT_DATA/design/pool1_pool2.sort.merged.padded20.cnv200.hg19.split_fusion_genes.210608.bed.gz"

mosdepth:
  extra: "--no-per-base --fast-mode"

msisensor_pro:
  PoN: "/PROJECT_DATA/PoN/Msisensor_pro_reference_nextseq_36.list_baseline"

purecn:
  extra: "--model betabin --mapping-bias-file /PROJECT_DATA/purecn/mapping_bias_nextseq_27_hg19.rds"
  normaldb: "/PROJECT_DATA/purecn/normalDB_nextseq_27_hg19.rds"
  intervals: "/PROJECT_DATA/purecn/targets_twist-gms-st_hg19_25000_intervals.txt"

purecn_coverage:
  intervals: "/PROJECT_DATA/purecn/targets_twist-gms-st_hg19_25000_intervals.txt"

report_fusions:
  annotation_bed: "/PROJECT_DATA/rna_fusion/Twist_RNA_fusionpartners.bed"

report_gene_fuse:
  filter_fusions: "/PROJECT_DATA/gene_fuse/filter_fusions_20230214.csv"

star:
  genome_index: "/sw/data/reference/Homo_sapiens/hg19/program_files/star/concat"
  extra: "--quantMode GeneCounts --sjdbGTFfile /sw/data/reference/Homo_sapiens/GRCh37/program_files/lifescope/refGene/refGene.hg19.20101221.gtf --outSAMtype BAM SortedByCoordinate --chimSegmentMin 10 --chimOutType WithinBAM SoftClip --chimJunctionOverhangMin 10 --chimScoreMin 1 --chimScoreDropMax 30 --chimScoreJunctionNonGTAG 0 --chimScoreSeparation 1 --alignSJstitchMismatchNmax 5 -1 5 5 --chimSegmentReadGapMax 3"

star_fusion:
  genome_path: "/sw/data/CTAT_RESOURCE_LIB/2021-03/GRCh37_gencode_v19_CTAT_lib_Mar012021.plug-n-play/ctat_genome_lib_build_dir/"
  
svdb_query:
  db_string: "--db /PROJECT_DATA/SVDB/all_TN_292_svdb_0.8_20220505.vcf --out_frq Twist_AF --out_occ Twist_OCC"

vep:
  vep_cache:  "/sw/data/vep/107"