---

 default_resources:
  threads: 1
  time: "4:00:00"
  mem_mb: 7000
  mem_per_cpu: 7000
  partition: "core"

 arriba:
  threads: 5
  time: "8:00:00"
  mem_mb: 35000
  mem_per_cpu: 7000

 bwa_mem:
  mem_mb: 112000
  mem_per_cpu: 7000
  threads: 16
  time: "8:00:00"

 fastp_pe:
  threads: 4
  mem_mb: 28000
  mem_per_cpu: 7000

 fuseq_wes:
  threads: 2
  mem_mb: 14000
  mem_per_cpu: 7000
  time: "24:00:00"

 fusioncatcher:
  threads: 8
  time: "16:00:00"
  mem_mb: 56000
  mem_per_cpu: 7000

 vep:
  threads: 4
  time: "6:00:00"
  mem_mb: 28000
  mem_per_cpu: 7000

 fastqc:
  threads: 2
  mem_mb: 14000
  mem_per_cpu: 7000

 manta_run_workflow_t:
  threads: 4
  time: "8:00:00"
  mem_mb: 28000
  mem_per_cpu: 7000

 gatk_mutect2_gvcf:
  threads: 1
  time: "8:00:00"
  mem_mb: 7000
  mem_per_cpu: 7000

 gatk_mutect2:
  threads: 1
  time: "8:00:00"
  mem_mb: 7000
  mem_per_cpu: 7000

 gene_fuse:
  threads: 8
  time: "8:00:00"
  mem_mb: 56000
  mem_per_cpu: 7000

 vardict:
  threads: 1
  time: "48:00:00"
  mem_mb: 7000
  mem_per_cpu: 7000

 star:
  threads: 4
  time: "8:00:00"
  mem_mb: 28000
  mem_per_cpu: 7000

 star_fusion:
  threads: 4
  time: "8:00:00"
  mem_mb: 28000
  mem_per_cpu: 7000
