name: Snakemake dry run

on:
  push:
    branches:
     - develop
     - master
  pull_request:
    branches:
     - develop
     - master
  workflow_dispatch:

jobs:
  snakemake-dry-run:
    name: Run snakemake dry run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
      - name: Install requirements.test.txt
        run: |
          pip install -r requirements.test.txt
      - name: snakemake dry run
        working-directory: .tests/integration
        run: |
          snakemake -n -s ../../workflow/Snakefile --configfiles ../../config/config.yaml config/config.yaml
      - name: snakemake dry run reference
        working-directory: .tests/integration
        run: | 
          snakemake -s ../../workflow/Snakefile_references.smk --configfiles ../../config/config.yaml ../../config/config_references.yaml config/config.yaml config/config_reference.yaml -n
